@baseURL= http://localhost:3000/api/
@name= products

###

# @name getAll
GET {{baseURL}}/{{name}}

###

# @name add
POST {{baseURL}}/{{name}}
Content-Type: application/json

{
    "name" : "Nike Air"
}

###

# @name update
PATCH {{baseURL}}/{{name}}/2
Content-Type: application/json

{
    "name" : "Laptop"
} 

###

# @name delete
DELETE {{baseURL}}/{{name}}/2

###

# @name pagination
GET {{baseURL}}/{{name}}?_page=5&_limit=4

### 

# @name pagination
GET {{baseURL}}/{{name}}?_page=2